/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ClienteDAO;
import model.Cliente;

/**
 *
 * @author cadup
 */
public class PainelCadastroCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form PainelCadastroCliente
     */
    public PainelCadastroCliente() {
        initComponents();
        Atualizatable();
    }
    
    public void Atualizatable(){
        DefaultTableModel tabela = (DefaultTableModel) roldados.getModel();
        ClienteDAO _clie = new ClienteDAO();
        tabela.setNumRows(0);
        
        try {
            for(Cliente clie: _clie.select()){
                tabela.addRow(new Object[]{
                    clie.getId_cliente(),
                    clie.getNome(),
                    clie.getCnh(),
                    clie.getDt_nasc(),
                    clie.getSexo()
                });
            }
        } catch (SQLException ex) {
            Logger.getLogger(PainelCadastroCarro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        inputnome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        inputcnh = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputsexo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputdata = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        roldados = new javax.swing.JTable();
        buttonupdate = new javax.swing.JButton();
        buttoncadastrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        inputid = new javax.swing.JTextField();
        buttondelete = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Nome");

        jLabel2.setText("N° da CNH 9 números");

        jLabel3.setText("Data-Nascimento  YYYY/MM/DD");

        jLabel4.setText("Sexo M ou F");

        roldados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CNH", "Nascimento", "Sexo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        roldados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roldadosMouseClicked(evt);
            }
        });
        roldados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                roldadosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(roldados);

        buttonupdate.setText("Update");
        buttonupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonupdateActionPerformed(evt);
            }
        });

        buttoncadastrar.setText("Cadastrar");
        buttoncadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoncadastrarActionPerformed(evt);
            }
        });

        jLabel5.setText("ou");

        jLabel6.setText("ID");

        buttondelete.setText("Deletar");
        buttondelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttondeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputsexo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(inputcnh, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(inputnome, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(inputdata, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(buttoncadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(28, 28, 28)
                        .addComponent(buttonupdate)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel6))
                            .addComponent(inputid, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(buttondelete)
                            .addGap(33, 33, 33))))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputcnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttoncadastrar)
                            .addComponent(jLabel5)
                            .addComponent(buttonupdate)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttondelete)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttoncadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoncadastrarActionPerformed
        ClienteDAO _cli = new ClienteDAO();
        Cliente cli = new Cliente();
        
        cli.setNome(inputnome.getText());
        cli.setCnh(inputcnh.getText());
        cli.setDt_nasc(inputdata.getText());
        cli.setSexo(inputsexo.getText());
        
        if(inputnome.getText().isEmpty() || inputcnh.getText().isEmpty() || inputdata.getText().isEmpty() || inputsexo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Confira se algo não está faltando");
        }else{
        
            DefaultTableModel tabela = (DefaultTableModel) roldados.getModel();

            Object[] dados = {
                cli.getId_cliente(),
                cli.getNome(),
                cli.getCnh(),
                cli.getDt_nasc(),
                cli.getSexo()
            };
            tabela.addRow(dados);

            try {
                _cli.insert(cli);
                Atualizatable();
                inputnome.setText("");
                inputcnh.setText("");
                inputdata.setText("");
                inputsexo.setText("");

                JOptionPane.showMessageDialog(null, "Cadastrado com Sucesso!");
            } catch (SQLException ex) {
                Logger.getLogger(PainelCadastroCarro.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Eroo ao Cadastrar!");
            }
        }
    }//GEN-LAST:event_buttoncadastrarActionPerformed

    private void buttonupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonupdateActionPerformed
        if(roldados.getSelectedRow() != -1){
            ClienteDAO _cli = new ClienteDAO();
            Cliente cli = new Cliente();

            cli.setNome(inputnome.getText());
            cli.setCnh(inputcnh.getText());
            cli.setDt_nasc(inputdata.getText());
            cli.setSexo(inputsexo.getText());
            cli.setId_cliente((int)roldados.getValueAt(roldados.getSelectedRow(), 0));
            
            _cli.update(cli);
            
            inputnome.setText("");
            inputcnh.setText("");
            inputdata.setText("");
            inputsexo.setText("");
            
            JOptionPane.showMessageDialog(null, "Atualizado com Sucesso!");

            
            Atualizatable();
        } 
    }//GEN-LAST:event_buttonupdateActionPerformed

    private void roldadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roldadosMouseClicked
        if(roldados.getSelectedRow() != -1){
            inputnome.setText(roldados.getValueAt(roldados.getSelectedRow(), 1).toString());
            inputcnh.setText(roldados.getValueAt(roldados.getSelectedRow(), 2).toString());
            inputdata.setText(roldados.getValueAt(roldados.getSelectedRow(), 3).toString());
            inputsexo.setText(roldados.getValueAt(roldados.getSelectedRow(), 4).toString());
        }
    }//GEN-LAST:event_roldadosMouseClicked

    private void roldadosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_roldadosKeyReleased
        if(roldados.getSelectedRow() != -1){
            inputnome.setText(roldados.getValueAt(roldados.getSelectedRow(), 1).toString());
            inputcnh.setText(roldados.getValueAt(roldados.getSelectedRow(), 2).toString());
            inputdata.setText(roldados.getValueAt(roldados.getSelectedRow(), 3).toString());
            inputsexo.setText(roldados.getValueAt(roldados.getSelectedRow(), 4).toString());
        }
    }//GEN-LAST:event_roldadosKeyReleased

    private void buttondeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttondeleteActionPerformed
        ClienteDAO _cli = new ClienteDAO();
        Cliente cli = new Cliente();

        _cli.delete(Integer.parseInt(inputid.getText()));
        Atualizatable();
        inputid.setText("");
        
        JOptionPane.showMessageDialog(null, "Removido com Sucesso!");
    }//GEN-LAST:event_buttondeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttoncadastrar;
    private javax.swing.JButton buttondelete;
    private javax.swing.JButton buttonupdate;
    private javax.swing.JTextField inputcnh;
    private javax.swing.JTextField inputdata;
    private javax.swing.JTextField inputid;
    private javax.swing.JTextField inputnome;
    private javax.swing.JTextField inputsexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable roldados;
    // End of variables declaration//GEN-END:variables
}
