/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.ClienteDAO;
import model.FuncionarioDAO;
import model.Funcionario;

/**
 *
 * @author cadup
 */
public class PainelCadastroFuncionario extends javax.swing.JInternalFrame {

    /**
     * Creates new form PainelCadastroFuncionario
     */
    public PainelCadastroFuncionario() {
        initComponents();
        Atualizatable();
    }
    
    public void Atualizatable(){
        DefaultTableModel tabela = (DefaultTableModel) roldados.getModel();
        FuncionarioDAO _fun = new FuncionarioDAO();
        tabela.setNumRows(0);
        
        try {
            for(Funcionario fun: _fun.select()){
                tabela.addRow(new Object[]{
                    fun.getId(),
                    fun.getNome(),
                    fun.getDt_nasc(),
                    fun.getSexo()
                });
            }
        } catch (SQLException ex) {
            Logger.getLogger(PainelCadastroCarro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        roldados = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        inputnome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        inputdata = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputsexo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputid = new javax.swing.JTextField();
        buttoncadastrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        buttonupdate = new javax.swing.JButton();
        buttondelete = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        roldados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Nascimento", "Sexo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        roldados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roldadosMouseClicked(evt);
            }
        });
        roldados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                roldadosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(roldados);

        jLabel1.setText("Nome");

        jLabel2.setText("Data-Nascimento  YYYY/MM/DD");

        jLabel3.setText("Sexo M ou F");

        jLabel4.setText("ID");

        buttoncadastrar.setText("Cadastrar");
        buttoncadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoncadastrarActionPerformed(evt);
            }
        });

        jLabel5.setText("ou");

        buttonupdate.setText("Update");
        buttonupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonupdateActionPerformed(evt);
            }
        });

        buttondelete.setText("Deletar");
        buttondelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttondeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonupdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttoncadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(inputnome)
                            .addComponent(jLabel2)
                            .addComponent(inputdata)
                            .addComponent(jLabel3)
                            .addComponent(inputsexo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(buttondelete))
                                    .addComponent(inputid, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(65, 65, 65)))))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(buttondelete))
                        .addGap(9, 9, 9)
                        .addComponent(inputdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttoncadastrar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(buttonupdate)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttoncadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoncadastrarActionPerformed
        FuncionarioDAO _fun = new FuncionarioDAO();
        Funcionario fun = new Funcionario();
        
        fun.setNome(inputnome.getText());
        fun.setDt_nasc(inputdata.getText());
        fun.setSexo(inputsexo.getText());
        
        if(inputnome.getText().isEmpty() || inputdata.getText().isEmpty() || inputsexo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Confira se algo não está faltando");
        }else{
        
            DefaultTableModel tabela = (DefaultTableModel) roldados.getModel();

            Object[] dados = {
                fun.getId(),
                fun.getNome(),
                fun.getDt_nasc(),
                fun.getSexo()
            };
            tabela.addRow(dados);

            try {
                _fun.insert(fun);
                Atualizatable();
                inputnome.setText("");
                inputdata.setText("");
                inputsexo.setText("");

                JOptionPane.showMessageDialog(null, "Cadastrado com Sucesso!");
            } catch (SQLException ex) {
                Logger.getLogger(PainelCadastroCarro.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Eroo ao Cadastrar!");

            }
        }
    }//GEN-LAST:event_buttoncadastrarActionPerformed

    private void roldadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roldadosMouseClicked
        if(roldados.getSelectedRow() != -1){
            inputnome.setText(roldados.getValueAt(roldados.getSelectedRow(), 1).toString());
            inputdata.setText(roldados.getValueAt(roldados.getSelectedRow(), 2).toString());
            inputsexo.setText(roldados.getValueAt(roldados.getSelectedRow(), 3).toString());
        }
    }//GEN-LAST:event_roldadosMouseClicked

    private void roldadosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_roldadosKeyReleased
        if(roldados.getSelectedRow() != -1){
            inputnome.setText(roldados.getValueAt(roldados.getSelectedRow(), 1).toString());
            inputdata.setText(roldados.getValueAt(roldados.getSelectedRow(), 2).toString());
            inputsexo.setText(roldados.getValueAt(roldados.getSelectedRow(), 3).toString());
        }
    }//GEN-LAST:event_roldadosKeyReleased

    private void buttonupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonupdateActionPerformed
        if(roldados.getSelectedRow() != -1){
            FuncionarioDAO _fun = new FuncionarioDAO();
            Funcionario fun = new Funcionario();

            fun.setNome(inputnome.getText());
            fun.setDt_nasc(inputdata.getText());
            fun.setSexo(inputsexo.getText());
            fun.setId((int)roldados.getValueAt(roldados.getSelectedRow(), 0));

            
            _fun.update(fun);
            
            inputnome.setText("");
            inputdata.setText("");
            inputsexo.setText("");
            
            JOptionPane.showMessageDialog(null, "Atualizado com Sucesso!");

            Atualizatable();
        }
    }//GEN-LAST:event_buttonupdateActionPerformed

    private void buttondeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttondeleteActionPerformed
        FuncionarioDAO _fun = new FuncionarioDAO();
        Funcionario fun = new Funcionario();

        _fun.delete(Integer.parseInt(inputid.getText()));
        Atualizatable();
        inputid.setText("");
        
        JOptionPane.showMessageDialog(null, "Removido com Sucesso!");
    
    }//GEN-LAST:event_buttondeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttoncadastrar;
    private javax.swing.JButton buttondelete;
    private javax.swing.JButton buttonupdate;
    private javax.swing.JTextField inputdata;
    private javax.swing.JTextField inputid;
    private javax.swing.JTextField inputnome;
    private javax.swing.JTextField inputsexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable roldados;
    // End of variables declaration//GEN-END:variables
}
