/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Carro;
import model.CarroDAO;
import model.Contrato;
import model.ContratoDAO;

/**
 *
 * @author cadup
 */
public class PainelCadastroContrato extends javax.swing.JInternalFrame {

    /**
     * Creates new form PainelCadastroContrato
     */
    public PainelCadastroContrato() {
        initComponents();
        Atualizatable();
    }
    
    public void Atualizatable(){
        DefaultTableModel tabela = (DefaultTableModel) roldados.getModel();
        ContratoDAO _con = new ContratoDAO();
        tabela.setNumRows(0);
        
        try {
            for(Contrato con: _con.select()){
                tabela.addRow(new Object[]{
                    con.getId(),
                    con.getData(),
                    con.getHora(),
                    con.getId_func(),
                    con.getId_clie(),
                    con.getId_car()
                });
            }
        } catch (SQLException ex) {
            Logger.getLogger(PainelCadastroCarro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        roldados = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        inputdata = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        inputhora = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputfunc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputcliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        inputcarro = new javax.swing.JTextField();
        buttoncadastrar = new javax.swing.JButton();
        buttonupdate = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        buttondelete = new javax.swing.JButton();
        inputid = new javax.swing.JTextField();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        roldados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Contrato", "Data", "Hora", "ID_Func", "ID_Cliente", "ID_Carro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        roldados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roldadosMouseClicked(evt);
            }
        });
        roldados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                roldadosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(roldados);

        jLabel1.setText("Data-Contrato  YYYY/MM/DD");

        jLabel2.setText("Hora   EX: 19:35");

        jLabel3.setText("ID_Func");

        jLabel4.setText("ID_Cliente");

        jLabel5.setText("ID_Carro");

        buttoncadastrar.setText("Cadastrar");
        buttoncadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoncadastrarActionPerformed(evt);
            }
        });

        buttonupdate.setText("Update");
        buttonupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonupdateActionPerformed(evt);
            }
        });

        jLabel6.setText("ou");

        jLabel7.setText("ID_Contra");

        buttondelete.setText("Deletar");
        buttondelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttondeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputcarro, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(inputfunc, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(inputcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(inputdata, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2)
                                        .addComponent(inputhora, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(inputid, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(buttondelete)))
                                    .addGap(67, 67, 67))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(127, 127, 127)
                                    .addComponent(jLabel7)
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonupdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttoncadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(71, 71, 71)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(buttondelete))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputhora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputfunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputcarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttoncadastrar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonupdate)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttoncadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoncadastrarActionPerformed
        ContratoDAO _con = new ContratoDAO();
        Contrato con = new Contrato();
        
        con.setData(inputdata.getText());
        con.setHora(inputhora.getText());
        con.setId_func(Integer.parseInt(inputfunc.getText()));
        con.setId_clie(Integer.parseInt(inputcliente.getText()));
        con.setId_car(Integer.parseInt(inputcarro.getText()));
        
        
        if(inputdata.getText().isEmpty() || inputhora.getText().isEmpty() || inputfunc.getText().isEmpty() || inputcliente.getText().isEmpty() || inputcarro.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Confira se algo não está faltando");
        }else{
        
            DefaultTableModel tabela = (DefaultTableModel) roldados.getModel();

            Object[] dados = {
                con.getId(),
                con.getData(),
                con.getHora(),
                con.getId_func(),
                con.getId_clie(),
                con.getId_car()
            };
            tabela.addRow(dados);

            try {
                _con.insert(con);
                Atualizatable();
                inputdata.setText("");
                inputhora.setText("");
                inputfunc.setText("");
                inputcliente.setText("");
                inputcarro.setText("");

                JOptionPane.showMessageDialog(null, "Cadastrado com Sucesso!");
            } catch (SQLException ex) {
                Logger.getLogger(PainelCadastroCarro.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Eroo ao Cadastrar!");

            }
        }
    }//GEN-LAST:event_buttoncadastrarActionPerformed

    private void buttonupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonupdateActionPerformed
        if(roldados.getSelectedRow() != -1){
            ContratoDAO _con = new ContratoDAO();
            Contrato con = new Contrato();

            con.setData(inputdata.getText());
            con.setHora(inputhora.getText());
            con.setId_func(Integer.parseInt(inputfunc.getText()));
            con.setId_clie(Integer.parseInt(inputcliente.getText()));
            con.setId_car(Integer.parseInt(inputcarro.getText()));
            con.setId((int)roldados.getValueAt(roldados.getSelectedRow(), 0));
            
            _con.update(con);
            
            inputdata.setText("");
            inputhora.setText("");
            inputfunc.setText("");
            inputcliente.setText("");
            inputcarro.setText("");
            
            JOptionPane.showMessageDialog(null, "Atualizado com Sucesso!");

            
            Atualizatable();
        } 
    }//GEN-LAST:event_buttonupdateActionPerformed

    private void roldadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roldadosMouseClicked
        if(roldados.getSelectedRow() != -1){
            inputdata.setText(roldados.getValueAt(roldados.getSelectedRow(), 1).toString());
            inputhora.setText(roldados.getValueAt(roldados.getSelectedRow(), 2).toString());
            inputfunc.setText(roldados.getValueAt(roldados.getSelectedRow(), 3).toString());
            inputcliente.setText(roldados.getValueAt(roldados.getSelectedRow(), 4).toString());
            inputcarro.setText(roldados.getValueAt(roldados.getSelectedRow(), 5).toString());
        }
    }//GEN-LAST:event_roldadosMouseClicked

    private void buttondeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttondeleteActionPerformed
        ContratoDAO _con = new ContratoDAO();
        Contrato con = new Contrato();

        _con.delete(Integer.parseInt(inputid.getText()));
        Atualizatable();
        inputid.setText("");
    }//GEN-LAST:event_buttondeleteActionPerformed

    private void roldadosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_roldadosKeyReleased
        if(roldados.getSelectedRow() != -1){
            inputdata.setText(roldados.getValueAt(roldados.getSelectedRow(), 1).toString());
            inputhora.setText(roldados.getValueAt(roldados.getSelectedRow(), 2).toString());
            inputfunc.setText(roldados.getValueAt(roldados.getSelectedRow(), 3).toString());
            inputcliente.setText(roldados.getValueAt(roldados.getSelectedRow(), 4).toString());
            inputcarro.setText(roldados.getValueAt(roldados.getSelectedRow(), 5).toString());
        }
    }//GEN-LAST:event_roldadosKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttoncadastrar;
    private javax.swing.JButton buttondelete;
    private javax.swing.JButton buttonupdate;
    private javax.swing.JTextField inputcarro;
    private javax.swing.JTextField inputcliente;
    private javax.swing.JTextField inputdata;
    private javax.swing.JTextField inputfunc;
    private javax.swing.JTextField inputhora;
    private javax.swing.JTextField inputid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable roldados;
    // End of variables declaration//GEN-END:variables
}
